### ISSUE TITLE
install extension offline, not compatible version

### ISSUE THREAD

**Issue by fenfei** [kbrose/vsc-python-indent#100]
I'm working with some webIDE with online version of vscode, and I cannot change the version of vscode. I can only install the extensions with downloaded package, but the current version is not compatible with the vs code I'm using, it's 1.56.0. Where could I download the previous/compatible version of your package?

**Comment by kbrose** [comment]
Hey @fenfei. I put the `.vsix` file on every [release](https://github.com/kbrose/vsc-python-indent/releases). It looks like [v1.14.2](https://github.com/kbrose/vsc-python-indent/releases/download/v1.14.2/vsc-python-indent-1.14.2.vsix) is my most recent release compatible with vscode 1.56.0.

Microsoft also keeps the most recent ~5 releases available on the [official marketplace](https://marketplace.visualstudio.com/items?itemName=KevinRose.vsc-python-indent).
