### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by InTh3N3t** [kbrose/vsc-python-indent#102]
- Issue Type: `Performance`
- Extension Name: `vsc-python-indent`
- Extension Version: `1.17.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Marco/AppData/Local/Temp/KevinRose.vsc-python-indent-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kbrose** [comment]
Did you mean to attach a file to this issue?

**Comment by kbrose** [comment]
Please re-open if you are able to provide more information. Closing for now.
