### ISSUE TITLE
keepHangingBracketOnLine doesn't seem to be working for square brackets

### ISSUE THREAD

**Issue by jkyeung** [kbrose/vsc-python-indent#104]
What the code looks like before pressing `enter`:

```python
foo = [|]
```

What I want the code to look like after pressing `enter`:

```python
foo = [
    |]
```

What the code actually looks like after pressing `enter`:

```python
foo = [
    |
]
```

This issue is specifically about square brackets. For parens and curly braces, this setting works as expected (thank you for that!).

I am presuming that this setting is *meant* to [apply to square brackets as well](https://github.com/kbrose/vsc-python-indent/issues/66#issuecomment-680080792). If that hasn't changed, and no one else has brought it up, then maybe there is something about my other VS Code settings or extensions that is somehow in conflict. I'll be glad to try stuff out and report back, if you have any ideas.

**Comment by kbrose** [comment]
Hey @jkyeung thanks for the heads up. I'm away from my computer for a while, but I'm hopeful this will be easy to fix once I am able.

**Comment by kbrose** [comment]
@jkyeung can you double check the behavior?

When I `Python Indent: Keep Hanging Bracket On Line` to _on_ then it behaves the way you want (keeping the square bracket on the second line instead of putting it alone on the third).

**Comment by jkyeung** [comment]
Closing as stale and unreproducible. See [my comment on #105](https://github.com/kbrose/vsc-python-indent/issues/105#issuecomment-1793048905)
