### ISSUE TITLE
Automatic dedent for return doesn't always work

### ISSUE THREAD

**Issue by jkyeung** [kbrose/vsc-python-indent#105]
What the code looks like before pressing Enter:

```python
def foo():
    return|
```

When I get to the above state by typing in the function from scratch, then pressing Enter produces this:

```python
def foo():
    return
    |
```

However, if I subsequently reposition the cursor to just after `return` and *then* press Enter, I get the expected

```python
def foo():
    return
|
```

I also get the correct auto-dedent if I am typing from scratch but press Enter here (note the space between `return` and the cursor):

```python
def foo():
    return |
```

The same issue occurs if I'm returning an expression that ends with a variable or any of the constants `None`, `True`, or `False`:

```python
def foo(x):
    return 3 + x|
```

After Enter:

```python
def foo(x):
    return 3 + x
    |
```

Before Enter (with space after `x`):

```python
def foo(x):
    return 3 + x |
```

After Enter:

```python
def foo(x):
    return 3 + x
|
```

The issue does *not* occur if the return expression ends with a numeric constant, string constant, or parenthesis:

```python
def foo(x):
    return x + 3|
```

After Enter:

```python
def foo(x):
    return x + 3
|
```

Before Enter:

```python
def foo(x):
    return 3 + (x)|
```

After Enter:

```python
def foo(x):
    return 3 + (x)
|
```

And to reiterate, the issue also does *not* occur, no matter what the return expression, if the return line was already previously typed, and I reposition the cursor back to the end of that line, and *then* press Enter.

I am also not noticing the issue with other keywords, such as `pass`, `raise`, `break`, or `continue`, which produce the correct auto-dedent without any extra spaces or cursor repositioning.

**Comment by kbrose** [comment]
@jkyeung similar to your previous issue, I cannot reproduce. In an empty python file, if I type the characters

`def foo():<enter>return<enter>`

I get

```python
def foo():
    return
|
```

Could you list what other extensions you have installed? I'm wondering if something is interacting poorly.

**Comment by jkyeung** [comment]
Complete list of installed extensions:

- AutoHotkey Plus Plus
- Code for IBM i
- Code for IBM i Walkthroughs
- IBMi Languages
- Jupyter
- Jupyter Keymap
- Jupyter Notebook Renderers
- Overtype
- Pylance
- Python
- Python Indent
- RPGLE Free
- RPGLE language tools

**Comment by kbrose** [comment]
None of those jump out at me, but could you also try to reproduce after toggling all other extensions else off (and restarting VS Code)?

Also just wanted to make sure you have the most up to date version of vsc-python-indent -- this happens to you in version 1.18?

**Comment by jkyeung** [comment]
Well, here is my user `settings.json`. I don't have any workspace settings.

```json
{
    "telemetry.telemetryLevel": "off",
    "editor.fontFamily": "'JetBrains Mono NL ExtraLight', Consolas, monospace",
    // "editor.fontFamily": "InputX, Consolas, 'Courier New', monospace",
    "editor.fontSize": 16,
    "editor.acceptSuggestionOnEnter": "off",
    "editor.find.autoFindInSelection": "never",
    "editor.rulers": [80],
    "editor.stickyTabStops": true,
    "editor.autoClosingOvertype": "always",
    "workbench.editor.splitOnDragAndDrop": false,
    "terminal.integrated.fontFamily": "Consolas",
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    "files.insertFinalNewline": true,
    "python.terminal.executeInFileDir": true,
    "pythonIndent.keepHangingBracketOnLine": true,
    "pythonIndent.useTabOnHangingIndent": false,

    "[python]": {
        "editor.fontFamily": "InputX, 'JetBrains Mono NL ExtraLight', Consolas",
    },
    "[rpgle]": {
        "editor.fontFamily": "'JetBrains Mono NL ExtraLight', Consolas",
        "editor.stickyTabStops": false,
        "editor.tabSize": 2,
        "files.trimFinalNewlines": false,
        "files.insertFinalNewline": false,
    },
    "[cl]": {
        "editor.fontFamily": "'JetBrains Mono NL ExtraLight', Consolas",
        "files.trimFinalNewlines": false,
        "files.insertFinalNewline": false,
    },

    "code-for-ibmi.showConnectionButtons": true,
    "code-for-ibmi.connectionSettings": [
        {
            "name": "MY_SYS",
            "objectFilters": [
                {
                    "name": "LIBRARY1 source",
                    "library": "LIBRARY1",
                    "object": "*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*"
                },
                {
                    "name": "LIBRARY2 source",
                    "library": "LIBRARY2",
                    "object": "*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*"
                },
                {
                    "name": "MY_USER source",
                    "library": "MY_USER",
                    "object": "*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*"
                }
            ],
            "libraryList": [
                "QGPL",
                "QTEMP",
                "LIBRARY1",
                "LIBRARY2",
                "QS36F",
                "OTHER_LIB",
                "XYZLIB"
            ],
            "autoClearTempData": false,
            "customVariables": [],
            "connectionProfiles": [],
            "ifsShortcuts": [
                "/home/MY_USER"
            ],
            "homeDirectory": "/home/MY_USER",
            "enableSQL": false,
            "tempLibrary": "ILEDITOR",
            "tempDir": "/tmp",
            "currentLibrary": "QGPL",
            "sourceFileCCSID": "*FILE",
            "autoConvertIFSccsid": false,
            "hideCompileErrors": [],
            "enableSourceDates": true,
            "sourceDateGutter": true,
            "clContentAssistEnabled": false,
            "encodingFor5250": "default",
            "terminalFor5250": "default",
            "setDeviceNameFor5250": false,
            "connectringStringFor5250": "localhost",
            "autoSaveBeforeAction": false,
            "sourceASP": null,
            "databaseBrowserList": [
                "MY_USER",
                "LIBRARY2",
                "QS36F"
            ]
        }
    ],
    "code-for-ibmi.connections": [
        {
            "name": "MY_SYS",
            "host": "MY_HOST.COM",
            "port": 22,
            "username": "my_user",
            "privateKey": null
        }
    ],
    "files.associations": {
        "*.SQLSCRIPT": "sql",
        "*.DDL": "sql",
        "*.mac": "xml"
    },
    "vscode-rpgle.rpgleLinterSupportEnabled": true,
    "vscode-rpgle.showFixedFormatOutline": true,
}
```

I will try a clean install when I get a chance.

**Comment by jkyeung** [comment]
I've just completely uninstalled VS Code on another computer, rebooted, and installed VS Code again. The only extensions I installed this time were Python (and the ones it installs automatically) and Python Indent. The behavior I've described above still happens.

**Comment by kbrose** [comment]
That's pretty strange. I would guess that we'd see more activity on this issue if others were experiencing the same thing, but it's really strange that on a fresh install you see the same behavior.

If you're willing to dedicate more time to debugging, you could try cloning this repo and setting up a development environment (see the [quickstart](https://github.com/kbrose/vsc-python-indent/blob/master/DEVELOP.md)). That would let you set debug points.

E.g. the behavior you're seeing almost looks like the indentation parser isn't being fed all the text up to the point of your cursor. You could set a debug point [here](https://github.com/kbrose/vsc-python-indent/blob/master/src/indent.ts#L36) and inspect the content of the `lines` and `position` (0-indexed position of your cursor) variables to see if they look right.

**Comment by jkyeung** [comment]
Thanks for the tips. I would love to try setting up a development environment, but right now it's much more time-effective for me to just live with the quirks that I'm getting.

**Comment by jkyeung** [comment]
Once the Pylance extension gained the ability to do sophisticated indentation itself (with `"editor.formatOnType": true`), I disabled Python Indent and was pretty happy with what Pylance was doing.

Until recently. Its indentation behavior [changed](https://github.com/microsoft/pylance-release/discussions/4534#discussioncomment-6919756) for no discernible benefit (depending on your preference, the new behavior was either identical to the old, or much worse).

So I've re-enabled Python Indent and interestingly, have not encountered this issue anymore! Since I can't reproduce it anymore, I'm closing this issue.

**Comment by jkyeung** [comment]
Closed as stale and unreproducible.

**Comment by kbrose** [comment]
Thanks for the follow-up!

**Comment by jkyeung** [comment]
Unfortunately, this is happening for me again on the computer I use for work. Doesn't happen on my computer for home.

I'm not going to bother reopening this issue, since it's probably just as hard to reproduce or debug as before. I kind of just wanted to update how things stand.
