### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by jkyeung** [kbrose/vsc-python-indent#114]
When installing or enabling the Python Indent extension, I get the message "Connection to server got closed. Server will not be restarted." from the Python extension.

This started happening relatively recently. I'm pretty sure it was something introduced by one of the last few releases of either VS Code or the Python extension that is no longer happy with your extension.

Is there anything that can be done about this? I'm hoping it's just a small adjustment.

**Comment by jkyeung** [comment]
A recent update (to either VS Code or the Python extension, not sure which) seems to have resolved this issue. At least I have not experienced it lately, so closing as unreproducible.

**Comment by jkyeung** [comment]
A recent update (to either VS Code or the Python extension, not sure which) seems to have resolved this issue. At least I have not experienced it lately, so closing as unreproducible.

**Comment by kbrose** [comment]
Thanks @jkyeung for following up. I never experienced this myself.
