### ISSUE TITLE
Causes big lags in the editor

### ISSUE THREAD

**Issue by dickreuter** [kbrose/vsc-python-indent#116]
Should come with a warning that currently the whole editor becomes very laggy. Maybe this can be fixed?

**Comment by kbrose** [comment]
That doesn't happen for me. I'm going to need a lot more information.

**Comment by XrayBravoGolf** [comment]
@dickreuter [Extension bisect feature](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) may be helpful if the problem goes away when Python Indent is the few only extensions enabled.

**Comment by kbrose** [comment]
I'm happy to re-open if more information is provided.

**Comment by dickreuter** [comment]
sorry, I deleted the plugin now.
