### ISSUE TITLE
Connection to server got closed. Server will not be restarted

### ISSUE THREAD

**Issue by needhelp222** [kbrose/vsc-python-indent#117]
Since I switched from Windows 11 to 10 I can no longer use Verse. I've tried everything. I'm even back on Windows 11. Everything doesn't work. Has anyone ever had this problem? 
![Screenshot 2024-02-07 074340](https://github.com/kbrose/vsc-python-indent/assets/159232267/edd5508a-0b6d-4cef-913d-686bf0b00022)

**Comment by kbrose** [comment]
What is Verse? Are you sure you posted this issue in the right place?
