### ISSUE TITLE
There is no formatter for 'python' files installed

### ISSUE THREAD

**Issue by eodeluga** [kbrose/vsc-python-indent#121]
![image](https://github.com/kbrose/vsc-python-indent/assets/16492558/eaf27933-d6d9-4b7b-aa77-45a07804feeb)

Have tried this VSCode settings config
```
"[python]": {
      "editor.defaultFormatter": "KevinRose.vsc-python-indent",
      "diffEditor.ignoreTrimWhitespace": false,
      "gitlens.codeLens.symbolScopes": [
        "!Module"
      ],
      "editor.formatOnType": true,
      "editor.wordBasedSuggestions": "off"
    }
 ```

**Comment by lishaduck** [comment]
This extension isn't a formatter. Install [Ruff](https://astral.sh/ruff) and set it `charliermarsh.ruff` (or black, if you prefer) instead.

**Comment by kbrose** [comment]
Yes, what @lishaduck said. This extension is not a formatter.
