### ISSUE TITLE
Extension doesn't work in unsaved buffer

### ISSUE THREAD

**Issue by cbrnr** [kbrose/vsc-python-indent#2]
I've tried your extension and I really like it! One thing I've noticed is that it doesn't work in an unsaved buffer (even after setting the language mode to Python) - would it be difficult to fix this?

**Comment by kbrose** [comment]
Can you upgrade to v0.3.0 and retry? Should be fixed by da332c2d118fa4b03d641e254893ed37e4816922.

**Comment by cbrnr** [comment]
Thanks, this works! Perfect! :smiley:
