### ISSUE TITLE
Incorrect line breaking in multi cursor mode

### ISSUE THREAD

**Issue by dziaineka** [kbrose/vsc-python-indent#25]
**Describe the bug**
Hello! Lines don't break properly when I press "enter" in multicursor mode.

Extension enabled:
![](https://s3.gifyu.com/images/enabled.gif)

Extension disabled:
![](https://s3.gifyu.com/images/disabled.gif)

**Environment (please complete the following information):**
 - OS: Manjaro
 - Version of `Python Indent 0.7.0
 - Version of Visual Studio Code 1.34.0

**Comment by kbrose** [comment]
I believe I resolved this in dbd125e7f3298d9f6240badbc589ba98375e874b, released in v0.8.1. Please upgrade and re-open if the issue persists.

Note for future readers, the extension will simply not run if you have multiple cursors. If you have multiple cursors and are expecting perfect python indentation on all of them when you press enter, you will be disappointed.
