### ISSUE TITLE
Pressing enter to auto-fill is broken

### ISSUE THREAD

**Issue by asdasd-123** [kbrose/vsc-python-indent#3]
When you're half way through typing a variable/function name and the text is ready to auto-fill, pressing Enter usually defaults to auto filling. In this is forces a new line and you're forced to only use Tab to auto fill.

I see no point where you would want a new line when the auto-fill options are up in python.
Any chance of reverting that functionality back to normal?

**Comment by kbrose** [comment]
Can you try upgrade to 0.4.0 and retry? Should be fixed by b00e1d31b4720e93546a7fb35638c90888f84836.

**Comment by asdasd-123** [comment]
Had to do a re-install because I wasn't getting an update option, but works perfect now. Thanks a bunch for this!
