### ISSUE TITLE
Incorrect indentation of "elif", "else", "except", "finally" keywords depending on their indent level before pressing ENTER

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [kbrose/vsc-python-indent#31]
The extension tries to handle `if` and `try` blocks by de-denting the current line based on whether the previous line was a control statement or not (pass, return, continue etc...). It assumes that the starting location of the new line is where the extension would have put it (this isn't always the case) and then de-dents in certain scenarios. Having the start of the line in a different location is where we get the issue. Examples that illustrate the extension's intended logic (the two examples produce the intended output correctly):

1) With `pass` statement before `enter`:

```python
def test():
    if x:
        pass|
```

After `enter`:

```python
def test():
    if x:
        pass
    |
```

2) With non-control statement before `enter`:

```python
def test():
    if x:
        some_code = ''|
```

After `enter`:

```python
def test():
    if x:
        some_code = ''
        |
```
After typing `else:`:

```python
def test():
    if x:
        some_code = ''
        else:|
```

After `enter`:

```python
def test():
    if x:
        some_code = ''
    else:
        |
```

However, a user might come back to an `if` statement and add an `else` statement such as this example (before pressing `enter`):

```python
def test():
    if x:
        some_code = ''
    else:|
```

We expect to see this after pressing `enter`:

```python
def test():
    if x:
        some_code = ''
    else:
        |
```

What the code actually looks like after pressing `enter`:

```python
def test():
    if x:
        some_code = ''
else:
|
```

The extra de-dent logic won't work properly unless the extension looks back to previous lines to find the location of the corresponding `if` or `try` statement to ensure it only de-dents `dedentKeywords` that need it. Removing lines 27-34 from [indent.ts](https://github.com/kbrose/vsc-python-indent/blob/master/src/indent.ts#L27-L34) solves the issue but requires the user to manually de-dent before typing `else:` in the case of the second example. That isn't so bad considering we have to do this anyway without the extension.

**Environment (please complete the following information):**
 - `Python Indent` version: [e.g. 1.0.0]
 - Visual Studio Code version: [e.g. 1.36.0]
 - OS: Windows 10 1809

**Comment by trotsky1997** [comment]
yeah,thank you!

**Comment by kbrose** [comment]
I'm tempted to remove this whole dedent on all the `else:`-like keywords. It was a [previously requested feature](https://github.com/kbrose/vsc-python-indent/issues/19), but it doesn't feel like the current implementation is really smooth or elegant. I ***wrote the extension*** and I still find myself still pressing shift-tab to dedent before typing `else:` out of habit.

I also think it might be impossible to be perfect, consider the following:

```python
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
            else:  # no way to know what level the user intends here
```

Maybe I'll make it a config/mark it as experimental or something...

**Comment by WhistleWhileYouWork** [comment]
Ahh, you're absolutely right! Even if you labored to fix the current issue, you are still faced with the possible ambiguity.

I suppose one could argue that the `else` should always belong to the current `if` and if it doesn't, user intervention is required. After all, we can't expect the extension to do _everything_ for us. I actually like the feature and would adapt to using it if this current issue could be resolved with minimal effort. Otherwise I agree with making it opt-in.

**Comment by jontaa** [comment]
> Ahh, you're absolutely right! Even if you labored to fix the current issue, you are still faced with the possible ambiguity.
> 
> I suppose one could argue that the `else` should always belong to the current `if` and if it doesn't, user intervention is required. After all, we can't expect the extension to do _everything_ for us. I actually like the feature and would adapt to using it if this current issue could be resolved with minimal effort. Otherwise I agree with making it opt-in.

+1 to this. An else: or elseif should always be on the same indentation level as the first if found above it. Unless it is manually placed further to the left

The below when pressing enter:
Put on the same indentation level of the next "if" found that is to the left indentation wise or on the same level from the "else:" that was written
Action: "else:" is indented one to the left
```python
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
            else:  # no way to know what level the user intends here
```

The below when pressing enter:
Put on the same indentation level of the next "if" found that is to the left indentation wise or on the same level from the "else:" that was written
Action: "else:" is not moved
```python
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
        else:  # no way to know what level the user intends here
```


The below when pressing enter:
Put on the same indentation level of the next "if" found that is to the left indentation wise or on the same level from the "else:" that was written
Action: "else:" is not moved
```python
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
    else:  # no way to know what level the user intends here
```

This does mean that if the else: writte in the second example was indented to be part of the first if statement, then it would need to be indented to the left manually, but this is nothing that the editor can be expected to know.

**Comment by DDriggs00** [comment]
Same issue: If I start with:
```py
def a(x):
    try:
        print('a')
    except:
```
and press enter, I get:
```py
def a(x):
    try:
        print('a')
except:
    
```

**Comment by kbrose** [comment]
I believe this behavior has been improved in v1.4.0. Please upgrade, and if you continue to have problems please create a new issue.
