### ISSUE TITLE
Detection of variable names as control statements e.g. 'return_x' treated as 'return'

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [kbrose/vsc-python-indent#33]
What the code looks like before pressing `enter`:

```python
def my_example():
    return_x = 1|
```

What I want the code to look like after pressing `enter`:

```python
def my_example():
    return_x = 1
    |
```

What the code actually looks like after pressing `enter`:

```python
def my_example():
    return_x = 1
|
```

The section in parseLines looks for dedentNextKeywords by using startswith() but that would allow any variable name starting with "return", "pass", "break", "continue" or "raise" to be counted as a keyword and the resulting dedent would be incorrect. I will submit a pull request shortly.

**Environment (please complete the following information):**
 - `Python Indent` version: [e.g. 1.1.0]
 - Visual Studio Code version: [e.g. 1.36.1]
 - OS: Windows 10 1809

**Comment by kbrose** [comment]
Released in 1.2.0, please upgrade and re-open if the issue persists.
