### ISSUE TITLE
Leaves indented white space if pressing ENTER on a line with no text

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [kbrose/vsc-python-indent#37]
As far as I can tell this occurs in nearly all circumstances. The only exception is for the line immediately following a `return` statement that ends a function. When on the line below the `return` statement, you TAB then press ENTER and the TAB is automatically removed.

I wouldn't classify this as a feature request since this is the default behavior of VSCode. Hopefully all that is required to implement this is to detect a non-text line and remove any white space while indenting the next line by that same amount of white space.

What the code looks like before pressing `enter`:

```python
def my_example():
    |  # We decide we want an additional blank line so we will press ENTER to move down 1 line
```

What I want the code to look like after pressing `enter`:

```python
def my_example():
# White space was removed from this line
    |
```

What the code actually looks like after pressing `enter`:

```python
def my_example():
    # White space was left here
    |
```

This can be very frustrating since the alternative is to either remove the white space, press RETURN _and then_ re-indent the new line _or_ press ENTER type out your code and go back later and delete the white space (probably after your linter gives you a bunch of warnings).

**Environment (please complete the following information):**
 - `Python Indent` version: [e.g. 1.2.0]
 - Visual Studio Code version: [e.g. 1.36.1]
 - OS: Windows 10 1809

**Comment by kbrose** [comment]
There's a setting to trim whitespace on save that you might find helpful. It'll show up if you search for "trim whitespace" in the settings. Below is the JSON version of the setting.

```
"files.trimTrailingWhitespace": true
```

**Comment by WhistleWhileYouWork** [comment]
Nice. I was just thinking there should be an extension that does this. This will save me loads of frustration. The last thing I want to have to worry about is whitespace.

I consider the issue a non-issue given there is a better solution. Should I close it?
