### ISSUE TITLE
No hanging indent after line continuation '\' without an enclosing (),[] or {}

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [kbrose/vsc-python-indent#38]
The default behavior for VSCode is to have a hanging indent. This issue does not occur if the `\` is inside `()`, `[]` or `{}`.

What the code looks like before pressing `enter`:

```python
def my_example():
    test = this + \|
```

What I want the code to look like after pressing `enter`:

```python
def my_example():
    test = this + \
        |    # Hanging indent
```

What the code actually looks like after pressing `enter`:

```python
def my_example():
    test = this + \
    |
```

**Environment (please complete the following information):**
 - `Python Indent` version: [e.g. 1.2.0]
 - Visual Studio Code version: [e.g. 1.36.1]
 - OS: Windows 10 1809

**Comment by kbrose** [comment]
Released in v1.3.0, please re-open if you still have issues.
