### ISSUE TITLE
else: incorrectly dedented

### ISSUE THREAD

**Issue by jontaa** [kbrose/vsc-python-indent#41]
As far as I can tell, the issue in https://github.com/kbrose/vsc-python-indent/issues/31 is still present in 1.4.0

Tested with the below. Put the cursor to the right of the "else:" and press enter. The else: indents on the the left even when there is no if statement on that level.
```
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
    else:
```

**Comment by WhistleWhileYouWork** [comment]
I copy/pasted your example and I can't reproduce your issue. I tested every permutation I could think of and so far it works as intended.

**Comment by kbrose** [comment]
@jontaa I also cannot reproduce

In both cases below, pressing `Enter` does not move the `else:` at all for me.

```python
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
    else:
```

```python
def my_function(x):
    if x > 0:
        if x == 5:
            print(x)
        else:
```

Please double check you are on v1.4.0, and if the issue persists could you list all installed extensions, and the version of VSCode?

**Comment by jontaa** [comment]
> @jontaa I also cannot reproduce
> 
> In both cases below, pressing `Enter` does not move the `else:` at all for me.
> 
> ```python
> def my_function(x):
>     if x > 0:
>         if x == 5:
>             print(x)
>     else:
> ```
> 
> ```python
> def my_function(x):
>     if x > 0:
>         if x == 5:
>             print(x)
>         else:
> ```
> 
> Please double check you are on v1.4.0, and if the issue persists could you list all installed extensions, and the version of VSCode?



> I copy/pasted your example and I can't reproduce your issue. I tested every permutation I could think of and so far it works as intended.

You are totally correct, while it said that my extension version was 1.4.0 a reload was required to start using the new version. Now after a reload I cannot reproduce any longer either. Very happy about this!
