### ISSUE TITLE
Allow indent using tabs instead of spaces

### ISSUE THREAD

**Issue by PunnyBoi** [kbrose/vsc-python-indent#42]
**Is your feature request related to a problem? Please describe.**
Hi. Is it possible to extend the functionality of this extension to 'Indent using Tab' also? I personally prefer Tab over Spaces because I find it easy to navigate in code when I use 'tab'.

**Describe the solution you'd like**
The extension works for 'Indent using Tab' too.

**Describe alternatives you've considered**
I am using 'Indent using Spaces' instead of 'using Tabs'

**Additional context**

**Comment by kbrose** [comment]
How would you want this to work when the indentation for the next line is not an even multiple of your indent size? Example:

```python
like_this = [0, 1, 2,
             3, 4, 5]
```

The second line is indented 13 spaces.

**Comment by PunnyBoi** [comment]
Right, I now see the problem. When I requested this feature, I only had the conditional-statements indentation in mind.

Looking at your example, suddenly a thought came to my mind that how Matlab do this? So I checked in the Matlab and I observe that regardless of the indentation of the first line (in our example `like_this = [0, 1, 2`), the indentation from the second line onward (in our example `3, 4, 5]`) is always the same and equals to four space (or a tab equal in length to four spaces). I agree that it doesn't look as beautiful as what it is now, but this can be a workaround. (Also, I want to emphasize that I have never used something similar to your example till now. Given the fact that indentation is important in Python, there is a chance what I suggested as a workaround will throw an indentation error. So please correct me if I am wrong.)

**Comment by kbrose** [comment]
```python
like_this = [0, 1, 2,
    3, 4, 5]
```

is perfectly valid Python, so there's no concern there. I wouldn't be opposed to adding an option for tab-based indentation to this to the extension, using the above style of indentation to continue bracket-style expressions.

However, I want to be clear that I probably will not spend time implementing this option myself. The [PEP8 style guide recommends using spaces](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces), and I get the impression that most people who write python nowadays are not using tabs. Not to say that you don't have a valid reason to use tabs, but I never use tabs and don't want to spend too much time on it.

**Comment by jkyeung** [comment]
> How would you want this to work when the indentation for the next line is not an even multiple of your indent size?

I don't use tabs myself, but if I did, I think there are at least three reasonable options:

1. Don't try to align with anything, just increase indent by one level.

2. Calculate alignment as though using all spaces, but then replace as many leading spaces as possible using tabs, according to the user's "spaces per indent" setting, and leave the remainder as spaces.

3. Calculate alignment as though using all spaces, but then replace *the current level of semantic indentation* with tabs (i.e. same number of tabs as the initial line), and leave the remainder as spaces.

I don't have a strong opinion about which of those is best. I agree it is completely reasonable to leave this as "pull requests welcome".

**Comment by kbrose** [comment]
I'm closing this issue -- I have no intention of supporting indentation with tabs.
