### ISSUE TITLE
VsCode issue : Fails to get new line after installing this extension 

### ISSUE THREAD

**Issue by varun-1004** [kbrose/vsc-python-indent#44]
**Describe the bug**
When I installed this extension on my VsCode Application, it failed as I was not able to add a new blank line (pressing the Enter key). 

**To Reproduce**

**Expected behavior**

**Screenshots:**
If you want, attach screenshots/videos/gifs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. ubuntu 18.04, Mac OS Mojave]
 - Version of `Python Indent` [e.g. 0.7.0]
 - Version of Visual Studio Code [e.g. 1.33.1]

**Additional context:**

**Comment by kbrose** [comment]
@varun-1004 to help diagnose this issue I'm going to need some more information.

Can you run the following command at your terminal and comment with the results?

```
code --list-extensions --show-versions
```

And (1) how did you install the extension, and (2) what version of VSCode are you running?

**Comment by varun-1004** [comment]
I installed the extension from within the VsCode itself. Version of intend-extension downloaded was 1.5.5. Currently using VsCode version : 1.37.1

**Comment by kbrose** [comment]
I think the problem may be an interaction between this extension and another extension you may have installed. Can you run the following command at your terminal and comment with the results?

```
code --list-extensions --show-versions
```

I don't know what you mean by "Version of intend-extension downloaded was 1.5.5".

**Comment by kbrose** [comment]
Please re-open if you can provide more information. As it stands, this issue is not reproducible.
