### ISSUE TITLE
Not auto-scroll when press Enter

### ISSUE THREAD

**Issue by zhongjimeiying** [kbrose/vsc-python-indent#46]
When I move the cursor to the end of last line at viewable area, and press Enter, cursor will disappear . When I disabled this extension and do same thing above, screen will auto-scroll. The default action when press Enter is to let cursor at viewable area. I think the default auto-scroll is worth keeping.

**Comment by kbrose** [comment]
Yeah, that's annoying. I'll be honest though I'm not sure how VSCode accomplishes their default behavior, so I don't know how hard it will be to fix.

**Comment by zhongjimeiying** [comment]
@kbrose thank you for telling me

**Comment by kbrose** [comment]
This should be fixed. Please upgrade to v1.7.0 and re-open if the issue persists.

**Comment by zhongjimeiying** [comment]
@kbrose grateful, you're awesome
