### ISSUE TITLE
the enter key do not work in vscode after uninstall this extension

### ISSUE THREAD

**Issue by lfjbb** [kbrose/vsc-python-indent#48]
![捕获](https://user-images.githubusercontent.com/35714131/68452244-dabf2d00-022c-11ea-9e83-bca691951dff.PNG)

**Comment by kbrose** [comment]
It makes it easier to understand bug reports if you take the time to clean up the text.

**Comment by kbrose** [comment]
Did you restart vscode after uninstalling?

**Comment by lfjbb** [comment]
I have restart vscode。 the reason of this problem is there two keybindings in vscode. I don't know why there two user defined keybindings  for the "enter" key。  anyway I remove the keybinding and everything is ok。thanks!
