### ISSUE TITLE
Extra line when inserting at beginning of hanging indent

### ISSUE THREAD

**Issue by f0k** [kbrose/vsc-python-indent#49]
**Minimal code example:**

What the code looks like before pressing `enter`:

```python
def my_example():
    x = {|
        0: 1,
    }
```

What I want the code to look like after pressing `enter`:

```python
def my_example():
    x = {
        |
        0: 1,
    }
```

What the code actually looks like after pressing `enter`:

```python
def my_example():
    x = {
        |
    
        0: 1,
    }
```

*Write a short description about why you want the behavior you have described.*

When inserting a new item at the beginning of a hanging-indent dictionary, I expected I could place the cursor after the opening bracket and then press return. It works correctly when placing it at the beginning of the first item, but that is a tad more difficult to achieve (sloppy mouse click to get to the end of the line, then press home).

**Environment (please complete the following information):**
 - `Python Indent` version: 1.5.0
 - Visual Studio Code version: 1.39.8
 - OS: Ubuntu 18.04

Thanks a lot for the plugin! :tada:

**Comment by kbrose** [comment]
That's no good. Thanks for the report.

**Comment by kbrose** [comment]
Hi @f0k 

I believe this is now fixed. Please update to v1.6.0 and re-open if the issue persists.

**Comment by f0k** [comment]
Wow, you're fast! Updated to v1.7.0 and it works fine. Thanks a lot for maintaining this! :+1:
