### ISSUE TITLE
Mind if we use your code in the Python extension for VS Code?

### ISSUE THREAD

**Issue by brettcannon** [kbrose/vsc-python-indent#57]
We are starting to look into fixing our indentation situation for https://github.com/microsoft/vscode-python and we realized your extension covers a lot of the cases we want to handle well. Do you have any qualms if we used your code to implement a solution? (I know your MIT license would allow use to copy without asking but it felt nicer to ask first. 😃 )

**Comment by kbrose** [comment]
No issues at all, I'd be honored. Be sure to also check out https://github.com/DSpeckhals/python-indent-parser written by @DSpeckhals with contributions from me as well.

@DSpeckhals do you have any qualms with the use of that library either?

**Comment by DSpeckhals** [comment]
@kbrose No qualms herr! It will be better to have this in core vs. an extension anyway. :smile:

**Comment by brettcannon** [comment]
@kbrose yep, we're aware of `python-indent-parser` as well.

@DSpeckhals @kbrose thanks to both of you for your support!

In case you're curious, our spike to research the topic has been tracked in https://github.com/microsoft/vscode-python/issues/8996. We don't have an ETA of when we will get to this (quarterly priorities are being worked out still), but this is definitely something we want to see solved.

Also know that we do appreciate you both putting the work that you have put in to help make up for us not getting to this issue yet.
