### ISSUE TITLE
brain storming

### ISSUE THREAD

**Issue by ctf0** [kbrose/vsc-python-indent#58]
am kinda in the same boat as u r, trying to hook into the `enter` event however i wanted to ask you

- why not use the `onDidChangeTextDocument` and check for the `content text` instead of overriding the enter key which is used in lots of places ?
- for the tabsize, you can instead get the previous line spaces by `prevLineText.match(/^\s+/)`

the ext am building https://github.com/ctf0/vscode-auto-expand-on-enter

**Comment by kbrose** [comment]
1. The parsing is a little hefty, running it on every key press seems a bit much. There's also been no reported issues from hooking onto the `Enter`, so in practice it doesn't seem like a problem.
2. Knowing how many spaces were in the previous line doesn't tell you the tab size (see below), why not just use the tab size as defined by the user?

```python
my_var = [0, 1, 2
          3, 4, 5,
          # indentation = 10???
```

**Comment by ctf0** [comment]
> The parsing is a little hefty

u r correct

> Knowing how many spaces were in the previous line doesn't tell you the tab size 

`\s` matches tab character as well
https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp

still, thanx for ur help.

**Comment by kbrose** [comment]
As mentioned in the [docs](https://github.com/kbrose/vsc-python-indent/blob/master/README.md), this extension does not support indentation using the tab character. (See https://github.com/kbrose/vsc-python-indent/issues/42 as well)

**Comment by ctf0** [comment]
got it
