### ISSUE TITLE
Indents to correct spacing, but moves the rest of the line too far.

### ISSUE THREAD

**Issue by asdasd-123** [kbrose/vsc-python-indent#6]
As the title states. The rest of the line gets shunted too far down. 
[Gif here](https://i.imgur.com/GyTRRow.gifv)

**Comment by kbrose** [comment]
Thanks for reporting the issue. Could you add code to the description of the issue instead of referring to a third party website? I believe you can also add attachments such as gifs to the issues directly if you'd prefer to do that.

**Comment by asdasd-123** [comment]
![2019-03-27_15-21-52](https://user-images.githubusercontent.com/35167513/55325159-1c5c4e00-547c-11e9-88d0-041a3238a2a9.gif)
Apologies, I couldn't work out how to attach something the first time round. It should be now.

A code example though would be:

- Initial code: (Cursor location is the # symbol in these cases)
`button.pack(#side="left", fill="both", expand="true", padx=10, pady=10)`

- Intended result after pressing enter 
`button.pack(
    #side="left", fill="both", expand="true", padx=10, pady=10)`

- Actual result
`button.pack(
    #
side="left", fill="both", expand="true", padx=10, pady=10)`

Hope this is more clear. 

Thanks

**Comment by kbrose** [comment]
Fix should be in v0.6.0
