### ISSUE TITLE
Blank lines retain the inserted indentation on Enter

### ISSUE THREAD

**Issue by thebertster** [kbrose/vsc-python-indent#60]
Using the editory without Python Indent installed, the auto-inserted indentation is removed when enter is pressed on a line which is otherwise blank. With Python Indent installed, we end up with trailing whitespace.

What the code looks like before pressing `enter`:

```python
def my_example():
    print('something')
····|
```

What I want the code to look like after pressing `enter`:

```python
def my_example():
    print('something')

····|
```

What the code actually looks like after pressing `enter`:

```python
def my_example():
    print('something')
····
····|
```
(· here denotes an actual space)

**Comment by thebertster** [comment]
This has been logged before (#37) and closed with a "better solution" of using the VS Code option to remove whitespace on save, but I personally don't like this option - if this is easy to resolve, I would rather have the option of retaining the behaviour of the default editor.

Thanks!

**Comment by kbrose** [comment]
VSCode's behavior around automatically trimming this whitespace is actually fairly complex: it is not just triggered by pressing the `Enter` key, and it is stateful. Currently this extension is only triggered by the `Enter` key (this extension actually makes the `Enter` key a keyboard shortcut for the indent behavior, not a feasible solution for every character on the keyboard), and is totally stateless.

To see this, create the following file (with this extension uninstalled/turned off), line numbers on the left for clarity.

```python
1 def my_example():
2     print('something')
3 ····
4 |
```

Make sure you put your cursor on line 4, the empty line. Then navigate back up to 3 and press `Enter`. Notice it does not delete the spaces.

```python
1 def my_example():
2     print('something')
3 ····
4 ····|
5 
```

This shows the behavior is _stateful_ -- if we hadn't navigated to line 4 before going back to line 3, then the spaces on line 3 would've been deleted. Without doing anything else, press the down arrow to go to line 5, and press any character, e.g. "a", and see that line 4 becomes empty.

```python
1 def my_example():
2     print('something')
3 ····
4 
5 a
```

This shows that the behavior is triggered by more than just `Enter`.

**Comment by kbrose** [comment]
All that said, I'm not opposed to adding a subset of VSCode's behavior. It'd probably make sense to start with just case when you press `Enter` on a line that only has whitespace in it. I think it'd make sense to wrap this in a parameter which is off by default, just so we don't mess up any existing workflows.

**Comment by thebertster** [comment]
Makes sense. For me, the difference that bugs me and that I notice all the time is the case I mentioned, so if we can do as you suggest and handle this limited case with a flag, that would be fantastic.

**Comment by kbrose** [comment]
There is a new setting `trimLinesWithOnlyWhitespace` that has the behavior we discussed above. Please update to at least version `1.10.0`.

Note that you might need to update vscode itself to `1.45.0` first.
