### ISSUE TITLE
Space after line break

### ISSUE THREAD

**Issue by doyou89** [kbrose/vsc-python-indent#62]
**Minimal code example:**

What the code looks like before pressing `enter`:

```python
result = my_func(first_argument, second_keyword=some_value1,| third_keyword=some_value2)
```

What I want the code to look like after pressing `enter`:
(no space between cursor and `third_keyword`)
```python
result = my_func(first_argument, second_keyword=some_value1,
                |third_keyword=some_value2)
```

What the code actually looks like after pressing `enter`:
(but space left between cursor and `third_keyword`)
```python
result = my_func(first_argument, second_keyword=some_value1,
                | third_keyword=some_value2)
```

**Comment by kbrose** [comment]
Thanks for the issue. Definitely not desired behavior.

I think one possible solution is to always trim whitespace to the right of the cursor before going into any of the additional logic, I'm just trying to think if there are legitimate use cases where we'd want to preserve that whitespace...

**Comment by MatthewFlamm** [comment]
To add to this, can it trim the whitespace if done this way?

```
result = my_func(first_argument, second_keyword=some_value1, |third_keyword=some_value2)
```

The desired result as in the initial post:
```
# Following line has no whitespace at the end
result = my_func(first_argument, second_keyword=some_value1,
                |third_keyword=some_value2)
```

The current behavior results in:

```
# Following line has a whitespace at the end
result = my_func(first_argument, second_keyword=some_value1, 
                |third_keyword=some_value2)
```

**Comment by doyou89** [comment]
> To add to this, can it trim the whitespace if done this way?
> 
> ```
> result = my_func(first_argument, second_keyword=some_value1, |third_keyword=some_value2)
> ```
> 
> The desired result as in the initial post:
> 
> ```
> # Following line has no whitespace at the end
> result = my_func(first_argument, second_keyword=some_value1,
>                 |third_keyword=some_value2)
> ```
> 
> The current behavior results in:
> 
> ```
> # Following line has a whitespace at the end
> result = my_func(first_argument, second_keyword=some_value1, 
>                 |third_keyword=some_value2)
> ```

In the above case, I think It should be left as it is intended.

**Comment by kbrose** [comment]
@MatthewFlamm I prefer to defer tasks like that to VSCode's `files.trimTrailingWhitespace` setting:

> When enabled, will trim trailing whitespace when saving a file.

**Comment by kbrose** [comment]
@doyou89 This should now be fixed. Make sure you upgrade to version 1.12.0 (or later) of the package.

If you have any issues with the behavior, please comment here or open a new issue.

Thank you for your patience!
