### ISSUE TITLE
Cannot create a newline in python scripts

### ISSUE THREAD

**Issue by harshsaini** [kbrose/vsc-python-indent#67]
I am not sure if this is a problem in my setup, however, this is a fresh install of the extension.

Whenever I create a new python file, I am unable to create newlines. Supposing I create a file named `test.py` and try to add a statement.
```
import os  # try to create a newline after this statement
```

I keep getting this error.

![image](https://user-images.githubusercontent.com/5178654/91209775-15f9f200-e6c1-11ea-9c64-6c376c00611c.png)

Here are my settings:

![image](https://user-images.githubusercontent.com/5178654/91210051-7db03d00-e6c1-11ea-961c-928e88e3d553.png)

**Comment by kbrose** [comment]
Hello @harshsaini, I'm sorry to hear that.

What other extensions do you have installed? If you disable all of them (except this extension), do you still have the problem?

**Comment by kbrose** [comment]
Cannot reproduce. I'm happy to open if I can get more info.
