### ISSUE TITLE
Doesn't work in python notebooks

### ISSUE THREAD

**Issue by ion-elgreco** [kbrose/vsc-python-indent#70]
The extension does not seem to work in .ipynb files.

**Comment by kbrose** [comment]
Hello @ion-elgreco!

I don't use notebooks often, and definitely not in VSCode, so this was not on my radar. I'll try and see if I can make that work.

**Comment by kbrose** [comment]
I looked into this, but it seems like notebook mode is significantly different from "text editor" mode. I couldn't even get my keybinding to register in the notebook mode. We'd probably need to ask the developers of the Python extension how we could edit text while in notebook mode.

**Comment by kbrose** [comment]
I'm hopeful that some of the proposed notebook APIs can be used once they're released. They seem helpful at first glance. https://code.visualstudio.com/updates/v1_50#_notebook-api

**Comment by kbrose** [comment]
I think this is now working as expected? I use notebooks rarely, and pretty much never use them within VS Code, but I just checked and it seems like the indentation behavior from this extension is happening.
