### ISSUE TITLE
Additional closing parentheses added

### ISSUE THREAD

**Issue by doyou89** [kbrose/vsc-python-indent#75]
Thanks for your work.

When you open a parentheses, closing parentheses is added automatically.
And then although you type closing parentheses, it won't added and just the cursor will be moved to the right.
But sometimes, closing parentheses is added.

### Normal case.
\# Step 1.
```python
d = {'a': |}
```
\# Step 2.
```python
d = {'a': [|]}
```
\# Step 3.
```python
d = {'a': [1,2|]}
```

And then write closing parentheses, but only cursor will be moved.
\# Step 4.
```python
d = {'a': [1,2]|}
```

### Bug case.
\# Step 1.
```python
d = {'a': |}
```
\# Step 2.
```python
d = {'a': [|]}
```
\# Step 3.
```python
d = {'a': [1,2|]}
```

Enter the return before closing parentheses, and add some more values.
\# Step 4.
```python
d = {'a': [1,2,
           3,4|]}
```

And then type closing parentheses. Closing parentheses added.
\# Step 5.
```python
d = {'a': [1,2,
           3,4]|]}
```

This bug happened for "]" and "}". I think other parentheses may be same.

**Comment by kbrose** [comment]
Hello @doyou89!

When I test this, I get the same behavior without the extension installed. It seems like this is a problem with VSCode itself, and not the python-indent extension.
