### ISSUE TITLE
The plug-in is not compatible with vscode-neovim

### ISSUE THREAD

**Issue by echaya** [kbrose/vsc-python-indent#82]
Hi, I've been trying out[ vscode-neovim ](https://github.com/asvetliakov/vscode-neovim) lately and seems it is not fully compatible with python-indent

The exact issue:

when pressing o in normal mode, it shall insert a line below the current cursor line. However with python-indent enabled, it enters insert mode and leave the cursor in the same line. 

I'm not entirely sure it is a python-indent issue or from vscode-neovim. But i have to give up python-indent for now as I'm migrating most workflow on vscode nowadays. 

Let me know if additional info is needed on the bug.

**Comment by kbrose** [comment]
Thanks for the note @echaya.

I'm hoping this will be a simple update to the condition here: https://github.com/kbrose/vsc-python-indent/blob/master/package.json#L46 (see `&& vim.mode =~ /(Insert|Replace|SurroundInputMode)/`) (see https://github.com/kbrose/vsc-python-indent/issues/10 for more information)

I've special cased the vim plugin, but perhaps the neovim plugin also needs to be included. I hope that they enable filtering in a similar way to the vim plugin. I'll try to dig in at some point in the near future.

**Comment by echaya** [comment]
thanks for the prompt reply @kbrose and looking forward to the update!

maybe neovim.mode == insert will just do the trick.

**Comment by kbrose** [comment]
Just double checking, is this the right extension? https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim

**Comment by kbrose** [comment]
@echaya is normal mode different than insert mode? (I don't use vim.)

If the python-indent extension only activated in insert mode, would that be correct behavior?

**Comment by echaya** [comment]
> Just double checking, is this the right extension? https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim

It is the right plug-in. 

> @echaya is normal mode different than insert mode? (I don't use vim.)
> 
> If the python-indent extension only activated in insert mode, would that be correct behavior?

Insert mode is the mode people typing out most of the code while normal mode is to move around the cursor and make small changes on existing text (or going into insert mode for big changes). So i guess it makes sense to only enable python-indent during the insert mode.

**Comment by kbrose** [comment]
@echaya can you try getting the latest version (1.14.2) and see if that fixes things?

**Comment by echaya** [comment]
it works!!!  Thanks much Kevin!
Best,
Frederick Z. Zhang, PhD, CFA
