### ISSUE TITLE
Which theme does demo.gif use?

### ISSUE THREAD

**Issue by guoaoo** [kbrose/vsc-python-indent#86]
What a comfortable theme, could I know its name? 😆
![demo](https://user-images.githubusercontent.com/34093221/120289775-3c098e00-c2f4-11eb-9257-022988356381.gif)

**Comment by kbrose** [comment]
Sure thing! I use "Palenight" from [community material themes](https://marketplace.visualstudio.com/items?itemName=equinusocio.vsc-community-material-theme). I've also tweaked the contrast of some border lines with the following settings:

```json
    "workbench.colorCustomizations": {
        "[Community Material Theme Palenight]": {
            "panel.border": "#00000030",
            "sideBar.border": "#00000030",
            "activityBar.border": "#00000030"
        }
    }
```

**Comment by guoaoo** [comment]
> Sure thing! I use "Palenight" from [community material themes](https://marketplace.visualstudio.com/items?itemName=equinusocio.vsc-community-material-theme). I've also tweaked the contrast of some border lines with the following settings:
> 
> ```json
>     "workbench.colorCustomizations": {
>         "[Community Material Theme Palenight]": {
>             "panel.border": "#00000030",
>             "sideBar.border": "#00000030",
>             "activityBar.border": "#00000030"
>         }
>     }
> ```

Thank you! I will download this theme and close this issue 😗
