### ISSUE TITLE
multiple indent blank lines will not clear white space before line

### ISSUE THREAD

**Issue by stolenzc** [kbrose/vsc-python-indent#95]
When I enable python-indent，I input multiple blank line which need indent，before all line will keep white space include before line，just like this pic：
![image](https://user-images.githubusercontent.com/42373706/168793764-db665d94-b206-46b2-acfb-15d6a67ff344.png)

(It will show all white space in my vscode)

but if I disable this plugin, It's will automatic delete white space, like this

![image](https://user-images.githubusercontent.com/42373706/168793697-c6a9f6b5-47ec-4698-b550-54067cd0c6d7.png)

I don't know this is a feature or a bug, if you need more information can ask me, hope your reply

**Comment by kbrose** [comment]
Hi @stolenzc -- have you tried setting the `trimLinesWithOnlyWhitespace` parameter? See the [README](https://github.com/kbrose/vsc-python-indent#trimming-whitespace-lines)

**Comment by stolenzc** [comment]
@kbrose Thank you very much for your reply, it really solved my problem.
