### ISSUE TITLE
Highlighting ` *` and pressing enter doesn't do anything.

### ISSUE THREAD

**Issue by aymather** [kbrose/vsc-python-indent#96]
Let's say you have some lines in your editor that looks like this:

```
literally anything here<PLACE CURSOR HERE> *
some more things
here
and<END HIGHLIGHT HERE>
here
```

Put your cursor in the place I identified, and hold shift and press down like you're highlighting the section. It's very important to place your cursor at the EXACT place I mentioned because it doesn't work anywhere else. It is also important that there is at **least** a single space between the starting cursor position and the `*` in order to reproduce the bug properly.

If you press down while holding shift to highlight the section, then press enter, I would expect the editor to delete everything that was highlighted and start a new line such that it would end up looking like this:

```
literally anything here

here
```

Instead, when you press enter, the editor won't delete anything and return your cursor to the same position it started in. So it looks like this

```
literally anything here<CURSOR ENDS UP HERE> *
some more things
here
and
here
```

After removing this extension, I'm no longer having this issue.

**Comment by kbrose** [comment]
Thanks for the detailed report @aymather -- I appreciate it. This should be fixed in the latest version (1.16.0).
