### ISSUE TITLE
python Indentation of the current line is automatically reduced after line wrap

### ISSUE THREAD

**Issue by zergtul** [kbrose/vsc-python-indent#98]
![image](https://user-images.githubusercontent.com/40799218/172977580-00b5fe56-7482-4e00-bc63-aab6e8d8e6c4.png)
press Enter at the end of line 54, like this:
![image](https://user-images.githubusercontent.com/40799218/172977681-1aab8424-1a9d-4669-a4eb-acbee5792d4a.png)
when i dissable python indent, press Enter like this:
![image](https://user-images.githubusercontent.com/40799218/172978011-08a3cb72-e9cf-4137-9397-38453f5e9a24.png)

code file:
[result_static.zip](https://github.com/kbrose/vsc-python-indent/files/8875268/result_static.zip)

**Comment by kbrose** [comment]
Thanks for the report @zergtul. I believe I've fixed this, I should be able to get a release out today with the update.

**Comment by kbrose** [comment]
This should be fixed in version 1.17.0
